# Generated by Django 5.0.3 on 2024-07-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veículo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
