# Generated by Django 5.0.3 on 2024-07-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veiculo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('cor', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=7)),
                ('km_entrada', models.IntegerField(blank=True, null=True)),
                ('km_saida', models.IntegerField(blank=True, null=True)),
                ('veiculo_institucional', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('função', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=7)),
                ('nome_do_condutor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
