# Generated by Django 5.0.7 on 2024-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0004_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
