# Generated by Django 5.0.3 on 2024-08-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0005_remove_usuario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='veiculo_institucional',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_do_condutor',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='veiculo_institucional',
            field=models.BooleanField(default=False),
        ),
    ]
