# Generated by Django 5.0.3 on 2024-08-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0007_rename_senha_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='tipo_do_condutor',
        ),
    ]
