# Generated by Django 5.0.3 on 2024-08-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0008_remove_veiculo_tipo_do_condutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='movimento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppPortaria.veiculo'),
        ),
    ]
