# Generated by Django 5.0.3 on 2024-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0009_remove_movimento_hora_alter_movimento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
