# Generated by Django 5.0.3 on 2024-08-13 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0010_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimento',
            name='saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
