# Generated by Django 5.0.3 on 2024-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortaria', '0011_movimento_entrada_movimento_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='entrada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='saida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
